[package]
edition = "2021"
name = "vulkan-tutorial"
version = "0.1.0"

[workspace]
members = ["vku"]

[dependencies]
ash = "0.36.0"
cstr = "0.2.9"
raw-window-handle = "0.3.4"
winit = "0.26.1"
thiserror = "1.0.30"

[dependencies.vku]
path = "vku"
