[package]
edition = "2021"
name = "vulkan-tutorial"
version = "0.1.0"
[dependencies]
ash = "0.36.0"
cstr = "0.2.9"
ash-window = "0.9.1"
raw-window-handle = "0.3.4"
winit = "0.26.1"
ouroboros = "0.14.2"
thiserror = "1.0.30"
