[package]
edition = "2021"
name = "vulkan-tutorial"
version = "0.1.0"

[workspace]
members = ["vku"]

[dependencies]
ash = "0.37"
cstr = "0.2"
raw-window-handle = "0.5"
winit = "0.28"
thiserror = "1.0"

[dependencies.vku]
path = "vku"
